ingress-nginx:
  controller:
    service:
      loadBalancerIP: 192.168.178.210
    allowSnippetAnnotations: true
    config:
      annotations-risk-level: Critical
    extraArgs:
      default-ssl-certificate: "cert-manager/default-tls"

  defaultBackend:
    enabled: true
    image:
      registry: registry.k8s.io
      image: ingress-nginx/custom-error-pages
      tag: v1.2.4@sha256:7d3a249020b277298e0695736b8e22c31185699b4531caeaa89fff31db5ad152

    extraVolumes:
      - name: custom-error-pages
        configMap:
          name: error-pages-cm

    extraVolumeMounts:
      - name: custom-error-pages
        mountPath: /www
