apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: {{ .Release.Name }}-secret
spec:
  forceRegenerate: false
  fields:
    - fieldName: "secret_key"
      encoding: "base64"
      length: "128"
    - fieldName: "admin_user"
      encoding: "base64"
      length: "32"
    - fieldName: "admin_password"
      encoding: "base64"
      length: "128"