apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: paperless-ngx-app
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: paperless-ngx-app
      annotations:
        reloader.stakater.com/auto: "true"
    spec:
      containers:
        - name: paperless-ngx-app
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
            - name: db-secret
              readOnly: true
              mountPath: "/run/secrets/db"
            - name: paperless-secret
              readOnly: true
              mountPath: "/run/secrets/paperless"
            - name: oidc-secret
              readOnly: true
              mountPath: "/run/secrets/oidc"
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-env-cm         
      volumes:
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-ngx-data-pvc
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-ngx-media-pvc
        - name: db-secret
          secret:
            secretName: paperless-ngx-db-app
        - name: paperless-secret
          secret:
            secretName: default-paperless-ngx-secret
        - name: oidc-secret
          secret:
            secretName: paperless-oidc-secret
---
kind: Service
apiVersion: v1
metadata:
  name: paperless-ngx-app-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: paperless-ngx-app
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80
