apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ngx-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-2
  resources:
    requests:
      storage: 20Gi
