apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: valetudo-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Authorization "Basic {{ b64enc .Values.valetudo.auth }}";

    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia-service.auth.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.{{ .Values.vadderung.baseDomain }}?rm=$request_method'
spec:
  ingressClassName: nginx
  rules:
    - host: "valetudo.{{ .Values.vadderung.baseDomain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: valetudo-service
                port:
                  number: 80
