vadderung:
  baseDomain: ~

longhorn:
  defaultSettings:
    # TODO: make configurable?
    defaultDataPath: /var/mnt/data-vol-1/longhorn/
    storageReservedPercentageForDefaultDisk: "10"
    defaultBackupBlockSize: "16"
  defaultBackupStore:
    backupTarget: s3://vadderung-3njqmakzogh34tmo8cyiae9lex21g83n8qjmivl1xhb9pnsyzjyps@eu-west/longhorn/
    backupTargetCredentialSecret: backup-s3-secret
    pollInterval: 300
