apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    namespace: infra
    server: {{ .Values.spec.destination.server }}

  # ArgoCD sync options
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      enabled: true
      prune: true

  sources:
    - path: apps/charts/cloudnativepg
      repoURL: {{ .Values.sources.chartRepo.url }}
      targetRevision: {{ .Values.sources.chartRepo.revision }}
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: {{ .Values.sources.valuesRepo.url }}
      targetRevision: {{ .Values.sources.valuesRepo.revision }}
      ref: values
