apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    namespace: infra
    server: {{ .Values.spec.destination.server }}

  # ArgoCD sync options
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      enabled: true
      prune: true

    sources:
      - repoURL: https://cloudnative-pg.github.io/charts
        chart: cloudnative-pg
        targetRevision: 0.26.0
      - repoURL: https://cloudnative-pg.github.io/charts
        chart: plugin-barman-cloud
        targetRevision: 0.2.0
