apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    namespace: infra
    server: {{ .Values.spec.destination.server }}

  # ArgoCD sync options
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: true

  # Helm chart
  source:
    chart: reflector
    repoURL: https://emberstack.github.io/helm-charts
    targetRevision: v9.1.37