apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cluster-backup-store
spec:
  configuration:
    destinationPath: "{{ .Values.vadderung.backup.s3bucket }}/cpg/"
    endpointURL: {{ .Values.vadderung.backup.s3endpoint }}
    s3Credentials:
      accessKeyId:
        name: infra-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: infra-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip