apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  goTemplate: false
  # goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        mergeKeys:
          - values.namespace
          - values.name
        generators:
          - git:
              repoURL: https://github.com/niphram/vadderung
              revision: HEAD
              directories:
                - path: kubernetes/apps/*/*
              values:
                namespace: "{{index .path.segments 2}}"
                name: "{{index .path.segments 3}}"
                chartPath: "{{.path.path}}"
          - git:
              repoURL: https://github.com/niphram/vadderung-values
              revision: HEAD
              files:
                - path: "values/*/*.yaml"
              values:
                namespace: "{{index .path.segments 1}}"
                name: "{{trimSuffix (ext .path.filename) .path.filename}}"
                valuesPath: "{{.path.path}}"
  template:
    metadata:
      name: "{{.values.namespace}}-{{.values.name}}"
    spec:
      # The project the application belongs to.
      project: default

      sources: []

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.values.namespace}}"

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
  templatePatch: |
    spec:
      sources:
        - path: "{{.values.chartPath}}"
          repoURL: https://github.com/niphram/vadderung
          targetRevision: HEAD
        {{- if .values.valuesPath }}
          helm:
            valueFiles:
              - $values/{{.values.valuesPath}}
        - repoURL: https://github.com/niphram/vadderung-values
          targetRevision: HEAD
          ref: values
        {{- end}}
