apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prod-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/niphram/vadderung
        revision: HEAD
        directories:
          - path: kubernetes/apps/*/*
  template:
    metadata:
      name: "{{index .path.segments 2}}-{{index .path.segments 3}}"
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      sources:
        - path: "{{.path.path}}"
          repoURL: https://github.com/niphram/vadderung
          targetRevision: HEAD
          helm:
            valueFiles:
              - $values/values.yaml
        - repoURL: https://github.com/niphram/vadderung-values
          targetRevision: HEAD
          ref: values

      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{index .path.segments 2}}"

      # Sync policy
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
          prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
          selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
