vadderung:
  baseDomain: ~

paperless:
  imagePullSecrets: []
  image:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    pullPolicy: IfNotPresent
    tag: latest
  service:
    port: 8000
  resources: {}

  podAnnotations:
    reloader.stakater.com/auto: "true"

  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

  volumeMounts:
    - name: paperless-data
      mountPath: /usr/src/paperless/data
    - name: paperless-media
      mountPath: /usr/src/paperless/media
    - name: db-secret
      readOnly: true
      mountPath: "/run/secrets/db"
    - name: paperless-secret
      readOnly: true
      mountPath: "/run/secrets/paperless"
    - name: oidc-secret
      readOnly: true
      mountPath: "/run/secrets/oidc"

  volumes:
    - name: paperless-data
      persistentVolumeClaim:
        claimName: paperless-ngx-data-pvc
    - name: paperless-media
      persistentVolumeClaim:
        claimName: paperless-ngx-media-pvc
    - name: db-secret
      secret:
        secretName: paperless-ngx-db-app
    - name: paperless-secret
      secret:
        secretName: default-paperless-ngx-secret
    - name: oidc-secret
      secret:
        secretName: paperless-oidc-secret

keydb:
  nodes: 2
  persistentVolume:
    # Use the postgres storage class for now
    storageClass: longhorn-postgres-replica-storage
