apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup
spec:
  cron: "0 0 * * *"
  task: "backup"
  retain: 1
  concurrency: 3
  groups:
    - default
  parameters:
    full-backup-interval: "14"
