apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre-deployment
spec:
  selector:
    matchLabels:
      app: calibre-app
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: calibre-app
    spec:
      # TODO:
      # initContainers:
      #   - name: plugin-downloader
      #     image: busybox:1.36
      #     command:
      #       - /bin/sh
      #       - -c
      #       - |
      #         wget -P /books https://github.com/noDRM/DeDRM_tools/releases/download/v10.0.3/DeDRM_tools_10.0.3.zip
      #         wget -P /books https://github.com/Leseratte10/acsm-calibre-plugin/releases/download/v0.0.16/DeACSM_0.0.16.zip
      # 
      #         chmod 777 /books/metadata.db
      #     volumeMounts:
      #       - name: calibre-plugins
      #         mountPath: /data
      #     resources:
      #       requests:
      #         cpu: 10m
      #         memory: 16Mi
      #       limits:
      #         cpu: 50m
      #         memory: 32Mi
      containers:
        - name: calibre-app
          image: {{ .Values.cwa.image }}
          volumeMounts:
            - name: calibre-data
              mountPath: /config
            - name: calibre-library
              mountPath: /calibre-library
            - name: calibre-ingest
              mountPath: /cwa-book-ingest
          ports:
            - containerPort: {{ .Values.cwa.port }}
              name: http
          {{- with (.Values.cwa).readinessProbe }}
          readinessProbe: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with (.Values.cwa).livenessProbe }}
          livenessProbe: {{- . | toYaml | nindent 12 }}
          {{- end }}
          {{- with (.Values.cwa).startupProbe }}
          startupProbe: {{- . | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: {{ .Values.cwa.tz }}
            - name: CWA_PORT_OVERRIDE
              value: {{ .Values.cwa.port | quote }}
        - name: calibre-downloader
          image: ghcr.io/calibrain/calibre-web-automated-book-downloader-tor:latest
          volumeMounts:
            - name: calibre-ingest
              mountPath: /cwa-book-ingest
          ports:
            - containerPort: 8084
              name: downloader-http
          env:
            - name: TZ
              value: {{ .Values.cwa.tz }}
      volumes:
        - name: calibre-data
          persistentVolumeClaim:
            claimName: calibre-data-pvc
        - name: calibre-library
          persistentVolumeClaim:
            claimName: calibre-library-pvc
        - name: calibre-ingest
          emptyDir:
            sizeLimit: 10Gi
