apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"

    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia-service.auth.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.{{ .Values.vadderung.baseDomain }}?rm=$request_method'
    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
spec:
  ingressClassName: nginx
  rules:
    - host: "books.{{ .Values.vadderung.baseDomain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: calibre-app-service
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-downloader-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"

    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia-service.auth.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.{{ .Values.vadderung.baseDomain }}?rm=$request_method'
    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
spec:
  ingressClassName: nginx
  rules:
    - host: "bookfinder.{{ .Values.vadderung.baseDomain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: calibre-downloader-service
                port:
                  number: 80
---
# Special Ingress for the upload endpoint with increased body size limit
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-upload-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    nginx.ingress.kubernetes.io/proxy-body-size: 10000m

    nginx.ingress.kubernetes.io/auth-method: 'GET'
    nginx.ingress.kubernetes.io/auth-url: 'http://authelia-service.auth.svc.cluster.local/api/authz/auth-request'
    nginx.ingress.kubernetes.io/auth-signin: 'https://auth.{{ .Values.vadderung.baseDomain }}?rm=$request_method'
    nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
spec:
  ingressClassName: nginx
  rules:
    - host: "books.{{ .Values.vadderung.baseDomain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/upload"
            backend:
              service:
                name: calibre-app-service
                port:
                  number: 80
---
# Special Ingress for the kobo sync endpoint that skips authentication
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calibre-ingress-kobo
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

    # Kobo sync fails otherwise (https://github.com/janeczku/calibre-web/wiki/Kobo-Integration#additional-hints)
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "1024k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4 512k"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "1024k"
    
    nginx.ingress.kubernetes.io/proxy-body-size: "50M"
spec:
  ingressClassName: nginx
  rules:
    - host: "books.{{ .Values.vadderung.baseDomain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/kobo"
            backend:
              service:
                name: calibre-app-service
                port:
                  number: 80
