kind: Service
apiVersion: v1
metadata:
  name: calibre-app-service
spec:
  selector:
    app: calibre-app
  ports:
    - name: calibre-app
      protocol: TCP
      targetPort: http
      port: 80
---
kind: Service
apiVersion: v1
metadata:
  name: calibre-downloader-service
spec:
  selector:
    app: calibre-app
  ports:
    - name: calibre-downloader
      protocol: TCP
      targetPort: downloader-http
      port: 80
