kind: Service
apiVersion: v1
metadata:
  name: calibre-app-service
spec:
  selector:
    app: calibre-app
  # type: LoadBalancer
  # loadBalancerIP: 192.168.178.211
  ports:
    - name: calibre-app
      protocol: TCP
      targetPort: http
      port: 80
