apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: lldap-db-object-store
spec:
  configuration:
    destinationPath: "{{ .Values.vadderung.backup.s3bucket }}/lldap/"
    endpointURL: {{ .Values.vadderung.backup.s3endpoint }}
    s3Credentials:
      accessKeyId:
        name: auth-s3-secret
        key: AWS_ACCESS_KEY_ID
      secretAccessKey:
        name: auth-s3-secret
        key: AWS_SECRET_ACCESS_KEY
    wal:
      compression: gzip
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap-db
spec:
  instances: 3
  description: "LLDAP DB"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: lldap-db-object-store

  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: longhorn-postgres-replica-storage
    size: 500Mi
  walStorage:
    storageClass: longhorn-postgres-replica-storage
    size: 1Gi

  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: lldap-db-backup
spec:
  cluster:
    name: lldap-db
  schedule: '0 0 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
