apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lldap-db
spec:
  instances: 3
  description: "LLDAP DB"

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cluster-backup-store

  primaryUpdateStrategy: unsupervised

  storage:
    storageClass: longhorn-postgres-replica-storage
    size: 500Mi
  walStorage:
    storageClass: longhorn-postgres-replica-storage
    size: 1Gi

  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead
