apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "pool-01"
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  cidrs:
  - start: "192.168.178.220"
    stop: "192.168.178.230"