apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: default-tls
  namespace: {{ .Release.Namespace }}
spec:
  secretName: default-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.vadderung.baseDomain }}
    - "*.{{ .Values.vadderung.baseDomain }}"